export const MEDIA_PATHS = {
    ICON: 'media/icon.svg',
    ICON_PNG: 'media/icon.png',
    ICON_DARK: 'media/icon-dark.svg',
    ICON_LIGHT: 'media/icon-light.svg',
    SOUND_ALERT: 'media/ding-ding-alert.mp3',
    STYLES_MAIN_CSS: 'media/styles/main.css',
    SCRIPT_MAIN_JS: 'media/main.js',
    SCRIPT_WEBVIEW_STATE_JS: 'media/webview/state.js',
    SCRIPT_WEBVIEW_MODAL_JS: 'media/webview/modal.js',
    SCRIPT_WEBVIEW_CONTROLS_POPOVERS_JS: 'media/webview/controls-popovers.js',
    SCRIPT_WEBVIEW_CONTROLS_DATETIME_JS: 'media/webview/controls-datetime.js',
    SCRIPT_WEBVIEW_CONTROLS_INPUT_JS: 'media/webview/controls-input.js',
    SCRIPT_WEBVIEW_FILTERS_JS: 'media/webview/filters.js',
    SCRIPT_WEBVIEW_TASKS_DND_JS: 'media/webview/tasks-dnd.js',
    SCRIPT_WEBVIEW_TASKS_CONTROLS_JS: 'media/webview/tasks-controls.js',
    SCRIPT_WEBVIEW_TASKS_RENDER_JS: 'media/webview/tasks-render.js',
    SCRIPT_WEBVIEW_CALENDAR_JS: 'media/webview/calendar.js',
    SCRIPT_WEBVIEW_UI_SHELL_JS: 'media/webview/ui-shell.js',
    SCRIPT_WEBVIEW_BRIDGE_JS: 'media/webview/bridge.js',
    FLATPICKR_CSS: 'media/flatpickr.min.css',
    FLATPICKR_DARK_CSS: 'media/flatpickr_dark.css',
    FLATPICKR_JS: 'media/flatpickr.min.js',
    CODICONS_CSS: 'node_modules/@vscode/codicons/dist/codicon.css'
} as const;
